contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #rnaflow channel"
    url: https://nfcore.slack.com/channels/rnaflow
    about: Discussion about the nf-core/rnaflow pipeline
